# Generated by Django 3.1.7 on 2021-06-20 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='location',
            new_name='sub_title',
        ),
        migrations.AddField(
            model_name='photo',
            name='img_num',
            field=models.IntegerField(default=0),
        ),
    ]
