# Generated by Django 3.2 on 2021-06-06 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mirim', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('author', models.TextField()),
                ('create_date', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
