# Generated by Django 3.2.4 on 2021-06-14 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(default='No Grade', max_length=10)),
                ('name', models.CharField(default='No Name', max_length=10)),
                ('email', models.CharField(default='No mail', max_length=15)),
                ('phone', models.CharField(default='No Number', max_length=15)),
                ('person', models.IntegerField(default=0)),
                ('photographer', models.CharField(default='Not Chose', max_length=10)),
                ('date', models.CharField(default='No Date', max_length=10)),
            ],
        ),
    ]
