# Generated by Django 3.2.4 on 2021-06-14 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='check',
            field=models.BooleanField(default=False, verbose_name='촬영 여부'),
        ),
        migrations.AlterField(
            model_name='group',
            name='date',
            field=models.CharField(default='No Date', max_length=10, verbose_name='예약 날짜'),
        ),
        migrations.AlterField(
            model_name='group',
            name='email',
            field=models.CharField(default='No mail', max_length=15, verbose_name='이메일'),
        ),
        migrations.AlterField(
            model_name='group',
            name='grade',
            field=models.CharField(default='No Grade', max_length=10, verbose_name='학번'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(default='No Name', max_length=10, verbose_name='이름'),
        ),
        migrations.AlterField(
            model_name='group',
            name='person',
            field=models.IntegerField(default=0, verbose_name='인원'),
        ),
        migrations.AlterField(
            model_name='group',
            name='phone',
            field=models.CharField(default='No Number', max_length=15, verbose_name='연락처'),
        ),
        migrations.AlterField(
            model_name='group',
            name='photographer',
            field=models.CharField(default='Not Chose', max_length=10, verbose_name='작가'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='check',
            field=models.BooleanField(default=False, verbose_name='촬영 여부'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='date',
            field=models.CharField(default='No Date', max_length=10, verbose_name='예약 날짜'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='email',
            field=models.CharField(default='No mail', max_length=15, verbose_name='이메일'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='grade',
            field=models.CharField(default='No Grade', max_length=10, verbose_name='학번'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='name',
            field=models.CharField(default='No Name', max_length=10, verbose_name='이름'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='phone',
            field=models.CharField(default='No Number', max_length=15, verbose_name='연락처'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='photographer',
            field=models.CharField(default='Not Chose', max_length=10, verbose_name='작가'),
        ),
    ]
