# Generated by Django 3.2.4 on 2021-06-16 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_auto_20210614_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='check',
            field=models.CharField(default='확정 대기', max_length=10, verbose_name='촬영 여부'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='check',
            field=models.CharField(default='확정 대기', max_length=10, verbose_name='촬영 여부'),
        ),
    ]
