# Generated by Django 3.1.7 on 2021-06-16 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_auto_20210616_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='email',
            field=models.CharField(default='No mail', max_length=25, verbose_name='이메일'),
        ),
        migrations.AlterField(
            model_name='group',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='email',
            field=models.CharField(default='No mail', max_length=25, verbose_name='이메일'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
