# Generated by Django 3.1.7 on 2021-06-17 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0012_auto_20210617_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='date',
            field=models.DateField(null=True, verbose_name='date'),
        ),
    ]
