# Generated by Django 3.1.7 on 2021-06-17 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0013_auto_20210617_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual',
            name='date_str',
            field=models.CharField(default='No date', max_length=30),
        ),
        migrations.AlterField(
            model_name='individual',
            name='date',
            field=models.IntegerField(default=0),
        ),
    ]
