# Generated by Django 3.1.7 on 2021-06-18 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0015_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual',
            name='review_check',
            field=models.BooleanField(default=False),
        ),
    ]
