# Generated by Django 3.1.7 on 2021-06-20 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0016_individual_review_check'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Individual',
            new_name='Reservation',
        ),
    ]
