# Generated by Django 3.1.7 on 2021-06-20 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0018_auto_20210621_0609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='date',
        ),
        migrations.AddField(
            model_name='review',
            name='date_str',
            field=models.CharField(default='No date', max_length=30),
        ),
    ]
