# Generated by Django 3.1.7 on 2021-06-21 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0019_auto_20210621_0611'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='grade',
            field=models.CharField(default='No Grade', max_length=20),
        ),
    ]
